/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoExtensionRequestRouteImport } from './routes/po-extension-request'
import { Route as AddCommunicationRouteImport } from './routes/add-communication'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications.settings'
import { Route as NotificationsSendCalendarRouteImport } from './routes/notifications.send-calendar'
import { Route as NotificationsReviewQueueRouteImport } from './routes/notifications.review-queue'
import { Route as NotificationsEscalationQueueRouteImport } from './routes/notifications.escalation-queue'

const PoExtensionRequestRoute = PoExtensionRequestRouteImport.update({
  id: '/po-extension-request',
  path: '/po-extension-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCommunicationRoute = AddCommunicationRouteImport.update({
  id: '/add-communication',
  path: '/add-communication',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSendCalendarRoute =
  NotificationsSendCalendarRouteImport.update({
    id: '/notifications/send-calendar',
    path: '/notifications/send-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotificationsReviewQueueRoute =
  NotificationsReviewQueueRouteImport.update({
    id: '/notifications/review-queue',
    path: '/notifications/review-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotificationsEscalationQueueRoute =
  NotificationsEscalationQueueRouteImport.update({
    id: '/notifications/escalation-queue',
    path: '/notifications/escalation-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-communication': typeof AddCommunicationRoute
  '/po-extension-request': typeof PoExtensionRequestRoute
  '/notifications/escalation-queue': typeof NotificationsEscalationQueueRoute
  '/notifications/review-queue': typeof NotificationsReviewQueueRoute
  '/notifications/send-calendar': typeof NotificationsSendCalendarRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/notifications/': typeof NotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-communication': typeof AddCommunicationRoute
  '/po-extension-request': typeof PoExtensionRequestRoute
  '/notifications/escalation-queue': typeof NotificationsEscalationQueueRoute
  '/notifications/review-queue': typeof NotificationsReviewQueueRoute
  '/notifications/send-calendar': typeof NotificationsSendCalendarRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/notifications': typeof NotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-communication': typeof AddCommunicationRoute
  '/po-extension-request': typeof PoExtensionRequestRoute
  '/notifications/escalation-queue': typeof NotificationsEscalationQueueRoute
  '/notifications/review-queue': typeof NotificationsReviewQueueRoute
  '/notifications/send-calendar': typeof NotificationsSendCalendarRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/notifications/': typeof NotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-communication'
    | '/po-extension-request'
    | '/notifications/escalation-queue'
    | '/notifications/review-queue'
    | '/notifications/send-calendar'
    | '/notifications/settings'
    | '/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-communication'
    | '/po-extension-request'
    | '/notifications/escalation-queue'
    | '/notifications/review-queue'
    | '/notifications/send-calendar'
    | '/notifications/settings'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/add-communication'
    | '/po-extension-request'
    | '/notifications/escalation-queue'
    | '/notifications/review-queue'
    | '/notifications/send-calendar'
    | '/notifications/settings'
    | '/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCommunicationRoute: typeof AddCommunicationRoute
  PoExtensionRequestRoute: typeof PoExtensionRequestRoute
  NotificationsEscalationQueueRoute: typeof NotificationsEscalationQueueRoute
  NotificationsReviewQueueRoute: typeof NotificationsReviewQueueRoute
  NotificationsSendCalendarRoute: typeof NotificationsSendCalendarRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/po-extension-request': {
      id: '/po-extension-request'
      path: '/po-extension-request'
      fullPath: '/po-extension-request'
      preLoaderRoute: typeof PoExtensionRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-communication': {
      id: '/add-communication'
      path: '/add-communication'
      fullPath: '/add-communication'
      preLoaderRoute: typeof AddCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/send-calendar': {
      id: '/notifications/send-calendar'
      path: '/notifications/send-calendar'
      fullPath: '/notifications/send-calendar'
      preLoaderRoute: typeof NotificationsSendCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/review-queue': {
      id: '/notifications/review-queue'
      path: '/notifications/review-queue'
      fullPath: '/notifications/review-queue'
      preLoaderRoute: typeof NotificationsReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/escalation-queue': {
      id: '/notifications/escalation-queue'
      path: '/notifications/escalation-queue'
      fullPath: '/notifications/escalation-queue'
      preLoaderRoute: typeof NotificationsEscalationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCommunicationRoute: AddCommunicationRoute,
  PoExtensionRequestRoute: PoExtensionRequestRoute,
  NotificationsEscalationQueueRoute: NotificationsEscalationQueueRoute,
  NotificationsReviewQueueRoute: NotificationsReviewQueueRoute,
  NotificationsSendCalendarRoute: NotificationsSendCalendarRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
